name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: plugin

    - name: Download pmmp files
      run: |
        curl -JLOs "https://jenkins.pmmp.io/job/PHP-7.4-Linux-x86_64/lastSuccessfulBuild/artifact/PHP_Linux-x86_64.tar.gz" &
        curl -JLOs "https://raw.githubusercontent.com/pmmp/DevTools/1.14/src/DevTools/ConsoleScript.php" &
        wait

    - name: Prepare php binary
      run: |
        echo "$(pwd)/bin/php7/bin" >> $GITHUB_PATH
        tar -xzf PHP_Linux-x86_64.tar.gz
        EXTENSION_DIR=$(find "$(pwd)/bin" -name *debug-zts*)
        echo "extension_dir=\"$EXTENSION_DIR\"" >> bin/php7/bin/php.ini
        sed -i "s/date.timezone=.*/date.timezone=Asia\\/Tokyo/" bin/php7/bin/php.ini

    - name: Build plugin
      run: |
        php -dphar.readonly=0 ConsoleScript.php --make plugin --out ${{ github.event.repository.name }}.phar

    - name: Create github release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          ${{ github.event.repository.name }}.phar
